ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "semantic_segmentation_augmentations"
  site-url: "https://ruescog.github.io/semantic_segmentation_augmentations"
  description: "A library to apply some data augmentations in semantic segmentation problems"
  twitter-card: true
  open-graph: true
  repo-branch: master
  repo-url: "https://github.com/ruescog/semantic_segmentation_augmentations"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/ruescog/semantic_segmentation_augmentations"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
