# AUTOGENERATED! DO NOT EDIT! File to edit: ../20_HolesFilling.ipynb.

# %% auto 0
__all__ = []

# %% ../20_HolesFilling.ipynb 2
from .iholesfilling import HolesFilling
from .cutoutrandom import CutOutRandom
from .cutoutsemantic import CutOutSemantic
from .cutouthideandseek import CutOutHideAndSeek
from .cutmixrandom import CutMixRandom
from .cutmixsemantic import CutMixSemantic
from .cutmixricap import CutMixRICAP
from .cutmixresizemix import CutMixResizeMix
from .carvemix import CarveMix
