# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_IHoleMakerTechnique.ipynb.

# %% auto 0
__all__ = ['HoleMakerTechnique']

# %% ../00_IHoleMakerTechnique.ipynb 2
import numpy as np

# %% ../00_IHoleMakerTechnique.ipynb 5
class HoleMakerTechnique():
    def __init__(self,
                 hole_size: tuple = (100, 100)): # The size of the hole in a tuple like (y, x).
        "Defines the size of the hole."
        self.hole_size = hole_size
        
    def get_hole(self,
             mask: np.ndarray): # The mask associated with the image where the hole is going to be made.
        "Defines how to make the hole."
        raise NotImplementedError("You can not use this abtract class to make a hole.")
