name: Deploy to GitHub Pages
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: py-actions/py-dependency-install@v3
        with:
          path: "./requirements.txt"
      - uses: fastai/workflows/quarto-ghp@master]
